# -*- coding: utf-8 -*-
"""eda_and_training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wjLRovTsxO-2YkcUDumPqQ-LlzEIYX6V
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from wordcloud import WordCloud

train_df = pd.read_csv('data/dreaddit-train.csv')
test_df = pd.read_csv('data/dreaddit-test.csv')

print(train_df.shape)
print(test_df.shape)

train_df.head()

train_df.isnull().sum()

train_df.info()

sns.countplot(x='label', data=train_df)
plt.title('Распределение классов')
plt.show()

train_df['text_length'] = train_df['text'].apply(len)

plt.figure(figsize=(10,5))
sns.histplot(train_df['text_length'], bins=50)
plt.title('Распределение длины сообщений')
plt.show()

sns.boxplot(x='label', y='text_length', data=train_df)
plt.title('Длина сообщений и стресс')
plt.show()

plt.figure(figsize=(10,5))
sns.histplot(train_df['sentiment'], bins=50)
plt.title('Распределение sentiment')
plt.show()

sns.boxplot(x='label', y='sentiment', data=train_df)
plt.title('Sentiment vs Stress')
plt.show()

stress_text = ' '.join(train_df[train_df['label'] == 1]['text'])

wordcloud = WordCloud(
    width=800,
    height=400,
    background_color='white'
).generate(stress_text)

plt.figure(figsize=(15,8))
plt.imshow(wordcloud)
plt.axis('off')
plt.title('WordCloud стрессовых сообщений')
plt.show()

import re
import string


def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'[^a-zA-Z ]', '', text)
    text = text.strip()
    return text


train_df['clean_text'] = train_df['text'].apply(clean_text)
test_df['clean_text'] = test_df['text'].apply(clean_text)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=5000,
    stop_words='english'
)

X_train = vectorizer.fit_transform(train_df['clean_text'])
X_test = vectorizer.transform(test_df['clean_text'])

y_train = train_df['label']
y_test = test_df['label']

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)

lr_pred = lr_model.predict(X_test)

print(accuracy_score(y_test, lr_pred))
print(classification_report(y_test, lr_pred))

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

print(accuracy_score(y_test, rf_pred))

from sklearn.naive_bayes import MultinomialNB

nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)

nb_pred = nb_model.predict(X_test)

print(accuracy_score(y_test, nb_pred))

from sklearn.svm import LinearSVC

svm_model = LinearSVC()
svm_model.fit(X_train, y_train)

svm_pred = svm_model.predict(X_test)

print(accuracy_score(y_test, svm_pred))

results = {
    'Logistic Regression': accuracy_score(y_test, lr_pred),
    'Random Forest': accuracy_score(y_test, rf_pred),
    'Naive Bayes': accuracy_score(y_test, nb_pred),
    'Linear SVM': accuracy_score(y_test, svm_pred)
}

results_df = pd.DataFrame(results.items(), columns=['Model', 'Accuracy'])
print(results_df)

sns.barplot(x='Accuracy', y='Model', data=results_df)
plt.title('Сравнение моделей')
plt.show()

import joblib

joblib.dump(lr_model, 'models/best_model.pkl')
joblib.dump(vectorizer, 'models/tfidf_vectorizer.pkl')